AWSTemplateFormatVersion: 2010-09-09

Description: Parameter to KeyName & ENV
Parameters:
  Keyname:
    Type: AWS::EC2::KeyPair::KeyName
   #Environment as Map
  Env:
    Description: Select Your Environment
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

#Mapping with AMI
Mappings:
 RegionMap:
    ap-southeast-2:
      AML: ami-0b3d7a5ecc2daba4c
      Rhel: ami-044c46b1952ad5861
    us-east-1:
      AML: ami-0533f2ba8a1995cf9
      Rhel: ami-096fda3c22c1c990a
    us-west-1:
      AML: ami-0a245a00f741d6301
      Rhel: ami-09d9c5cdcfb8fc655
  # Mapping Environment
 ENVmap:
    Dev: 
     Type: t2.micro
    Prod:
     Type: t2.small
#Condition for Environment
Conditions:
  #Description: Setting condition for Prod
   PEIP: !Equals [!Ref Env, 'prod']

Resources: 
  EC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - Rhel
      InstanceType: !FindInMap
        - ENVmap
        - !Ref Env
        - Type
      KeyName: !Ref Keyname
#Adding EIP
  MyProdEIP:
   Type: 'AWS::EC2::EIP'
   Condition: PEIP
   Properties:
      InstanceId: !Ref EC2Instance
   