AWSTemplateFormatVersion: 2010-09-09
Resources: 
  DevEC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-044c46b1952ad5861
      InstanceType: t2.micro
      KeyName: sydney
      SecurityGroups: 
        #- default
        - !Ref ssh

  ssh:
    Type: 'AWS::EC2::SecurityGroup'
    Properties: 
      GroupDescription: To Allow Http
      GroupName: Http_Access
      SecurityGroupIngress:
       - IpProtocol: tcp
         CidrIp: 0.0.0.0/0
         FromPort: 443
         ToPort: 443
