AWSTemplateFormatVersion: 2010-09-09

Description: Parameter to KeyName
Parameters:
  #Instance Type as Parameter
  TypeEC2:
    Description: Select Instance Type from List
    Type: String
    Default: t2.micro
    AllowedValues:
      - t1.micro
      - t2.micro
      - t2.small

#Mapping with AMI
Mappings:
 RegionMap:
    ap-southeast-2:
      AML: ami-0b3d7a5ecc2daba4c
      Rhel: ami-044c46b1952ad5861
    us-east-1:
      AML: ami-0533f2ba8a1995cf9
      Rhel: ami-096fda3c22c1c990a
    us-west-1:
      AML: ami-0a245a00f741d6301
      Rhel: ami-09d9c5cdcfb8fc655

Resources: 
  EC2Instance: 
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: !FindInMap
        - RegionMap
        - !Ref AWS::Region
        - Rhel
      InstanceType: !Ref TypeEC2
      #KeyName: !Ref KeyName